package parser

type Preposition string
const (
	PREP_ABOUT = "about"
	PREP_ABOVE = "above"
	PREP_ACROSS = "across"
	PREP_AGO = "ago"
	PREP_AT	= "at"
	PREP_BEFORE = "before"
	PREP_BELOW = "below"
	PREP_BESIDE = "beside"
	PREP_BY = "by"
	PREP_FOR = "for"
	PREP_FROM = "from"
	PREP_IN = "in"
	PREP_INTO = "into"
	PREP_NEXT_TO = "next to"
	PREP_OFF = "off"
	PREP_ON = "on"
	PREP_ONTO = "onto"
	PREP_OUT_OF = "out of"
	PREP_OVER = "over"
	PREP_PAST = "past"
	PREP_SINCE = "since"
	PREP_TILL = "till"
	PREP_THROUGH = "through"
	PREP_TO = "to"
	PREP_TOWARDS = "towards"
	PREP_UNDER = "under"
	PREP_UNTIL = "until"
)

var TIME_PREPOSITIONS = []string{
	PREP_AGO, PREP_AT, PREP_BEFORE, PREP_BY, PREP_FOR, PREP_IN, PREP_ON,
	PREP_PAST, PREP_SINCE, PREP_TILL, PREP_UNTIL, PREP_TO,
}

var LOCATION_PREPOSITIONS = []string{
	PREP_ABOVE, PREP_ACROSS, PREP_AT, PREP_BELOW, PREP_BESIDE, PREP_BY,
	PREP_FROM, PREP_IN, PREP_INTO, PREP_NEXT_TO, PREP_ON, PREP_ONTO,
	PREP_OVER, PREP_THROUGH, PREP_TO, PREP_TOWARDS, PREP_UNDER,
}

var ALL_PREPOSITIONS = []string{
	PREP_ABOUT, PREP_ABOVE, PREP_ACROSS, PREP_AGO, PREP_AT, PREP_BEFORE,
	PREP_BELOW, PREP_BESIDE, PREP_BY, PREP_FOR, PREP_FROM, PREP_IN,
	PREP_INTO, PREP_NEXT_TO, PREP_OFF, PREP_ON, PREP_ONTO, PREP_OUT_OF,
	PREP_OVER, PREP_PAST, PREP_SINCE, PREP_TILL, PREP_THROUGH,
	PREP_TO, PREP_TOWARDS, PREP_UNDER, PREP_UNTIL,
}

var SINGLE_WORD_PREPOSITIONS = []string{
	PREP_ABOUT, PREP_ABOVE, PREP_ACROSS, PREP_AGO, PREP_AT, PREP_BEFORE,
	PREP_BELOW, PREP_BESIDE, PREP_BY, PREP_FOR, PREP_FROM, PREP_IN,
	PREP_INTO, PREP_OFF, PREP_ON, PREP_ONTO, PREP_OVER, PREP_PAST,
	PREP_SINCE, PREP_TILL, PREP_THROUGH, PREP_TO, PREP_TOWARDS, PREP_UNDER,
	PREP_UNTIL,
}

var DOUBLE_WORD_PREPOSITIONS = []string{
	PREP_NEXT_TO, PREP_OUT_OF,
}

type Command struct {
	verb	string
	dobj	string
	prep	string
	iobj	string
	args	[]string
	argStr  string
}
